replicaCount: 1

image:
  repository: fn.xoto.cc/xoto/demo
  tag: 1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: xoto.cc
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"


global:
  env: {}

env: {}


