name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # 仅在 PR 合并到 master 时触发

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        run: |
          chmod +x mvnw
          cd application
          ../mvnw compile jib:build

      - name: Package Helm Chart
        run: |
          cd charts
          helm package helm-prod/ -d .

      - name: Push Helm Chart to self-hosted registry
        run: |
          helm repo add my-charts https://registry.xoto.cc
          helm cm-push *.tgz my-charts
